### About this notebook: 
<font color='grey'>
</font>

In [7]:
import sys
import matplotlib.pyplot as plt
import pandas as pd
import scipy
from scipy import stats 
import numpy as np
import json
import statsmodels.stats.multitest as multi
import matplotlib.pyplot as plt
import math
sys.path.append('../scripts/')
import Docket_integration

### Define the input directory and the output directory: 
<font color='grey'> 
    "input_dir": directory of input data<br/>
    "output_dir":directory of output data<br/>
</font>

In [3]:
directories = {"input_dir":"../Data_input_for_BRCA",
               "output_dir":"../Output_BRCA"}

### About the input file and the output files: 
<font color='grey'> 
    "File1": the mutation file from the cell line data;<br/>
    "File2": the mutation file from the patient derived somatic mutations;<br/>
    "File_out": the output file for the list of genes which show high similarity between two files;<br/>
    "Disease_type": The tumor types of the mutation data
</font>

In [9]:
input_data = {"input_file_1":"Mut_GDSC_matirx.csv",
"input_file_2":"Exp_GDSC_matirx.csv",
"output_file":"mut_expr_merge.csv",
}

In [15]:
input_data2 = {"Mutlist": ["TP53"],
"Exprlist": [],
"Output":"mut_exp_pair.csv",
}

In [16]:
Mut_mat = pd.read_csv(directories['input_dir'] + '/' + input_data['input_file_1'], index_col = "Unnamed: 0")
Expr_matrix = pd.read_csv(directories['input_dir'] + '/' + input_data['input_file_2'], index_col = "Unnamed: 0")

In [17]:
label_for_merge = Docket_integration.matrix_comp(Mut_mat,Expr_matrix )

Part of the objects in rows are identical!

In [18]:
if label_for_merge[0] > 0.9:
    Merged_mat = Docket_integration.merge_matrix(Mut_mat, Expr_matrix, 'Row','Row')
elif label_for_merge[1] > 0.9:
    Merged_mat = Docket_integration.merge_matrix(Mut_mat, Expr_matrix, 'Col','Col')
    
Merged_mat.to_csv(directories['output_dir'] + '/' +input_data['output_file'])

In [19]:
if len(input_data2['Mutlist']) > 0:
    Features_groupA = input_data2['Mutlist']
    Features_groupA = list(set(Features_groupA).intersection(set(list(Mut_mat.columns.values))))
else:
    Features_groupA = list(Mut_mat.columns.values)

if len(input_data2['Exprlist']) > 0:
    Features_groupB = input_data2['Exprlist']
    Features_groupB = list(set(Features_groupB).intersection(set(list(Expr_matrix.columns.values))))
else:
    Features_groupB = list(Expr_matrix.columns.values)


result = Docket_integration.Integration_category_numeric(Merged_mat, Features_groupA, Features_groupB)

In [23]:
result.to_csv(directories['output_dir'] + '/' + input_data2['Output'])

In [24]:
result.sort_values(by = ['p'])

         F1            F2             p        SE       FDR      -logP
11720  TP53     PRDM6_Exp  8.402837e-07 -1.646308  0.014637  13.989526
11625  TP53  PPP1R15B_Exp  5.345364e-06 -1.547962  0.046555  12.139281
8808   TP53      MDM4_Exp  9.632921e-06 -1.513766  0.055932  11.550324
17405  TP53    ZSWIM5_Exp  1.340046e-05 -1.493919  0.058356  11.220221
16884  TP53     ZMAT1_Exp  1.963464e-05 -1.470308  0.068403  10.838215
...     ...           ...           ...       ...       ...        ...
11197  TP53    PIK3CD_Exp  9.996177e-01  0.000181  0.999847   0.000382
7380   TP53     JAZF1_Exp  9.998167e-01 -0.000087  0.999983   0.000183
12159  TP53     RAB18_Exp  9.999280e-01 -0.000034  0.999983   0.000072
8039   TP53     LCE1B_Exp  9.999497e-01  0.000024  0.999983   0.000050
6238   TP53      GRB7_Exp  9.999834e-01  0.000008  0.999983   0.000017

[17419 rows x 6 columns]

In [25]:
result.loc[result['FDR'] < 0.05].sort_values(by = ['FDR'])

         F1            F2             p        SE       FDR      -logP
11720  TP53     PRDM6_Exp  8.402837e-07 -1.646308  0.014637  13.989526
11625  TP53  PPP1R15B_Exp  5.345364e-06 -1.547962  0.046555  12.139281